language: nodejs
node_js:
  - 0.7
notifications:
  email: false
before_script:
  - node --version
  - sudo npm install grunt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # node .lint/linter.js
  # node ./qunit/server.js /../ 8080 &
  # sleep 3
script:
  - grunt
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true'
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true&jquery=1.7'
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true&jquery=1.6'
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true&jquery=1.5'
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true&jquery=1.4'
  - /usr/local/bin/phantomjs ./qunit/runner.js 'http://localhost:8080/tests/jquery.sprite-animation.js.test.html?noglobals=true&jquery=1.3'